### PR TITLE
razerdefault22: Add en_US keymap

### PR DESCRIPTION
**Pull request by germ**
Turns out it was easier then I thought, no idea on how the logo is controlled but mines painted over anyway !

### CODE REVIEW

**Comment by z3ntu** [comment]
Quick feedback: The labels should be lower case like they are on the actual keys.
Also, e.g. for the arrows, super, etc you can copy-paste the \usomething labels you find in the layouts.
I'll take a closer look tomorrow.

**Comment by germ** [comment]
Will update :)

**Comment by z3ntu** [comment]
Btw logo is normally some Matrix position like [0, 20] but I don't have that LED added as I don't know where I should put it in the layout so it looks good.

**Comment by germ** [comment]
Sorry it took a while to update, forgot to drag my keyboard to work for testing. Sort of hard to preview layouts when you can't access the panel. Should be good to merge!

**Comment by z3ntu** [comment]
argh, I tried to push a rebase to your repo but I pushed a no-change commit to your master so github decided to close the PR and deny me any follow-up pushes to your repo.
Anyways, your commit (plus a few adjustments) are in master :)

**Pull request closed without merging**
