### PR TITLE
Bulgarian translation

### PR DESCRIPTION
**Pull request by ShinniUwU**
I rewrote the Russian translation to Bulgarian directly in the GitHub editor without downloading any apps or following the instructions, as I have ADHD. Unfortunately, I couldn't manage to do so. If I made any mistakes or missed anything, please let me know so I can correct it <33.

### CODE REVIEW

**Comment by z3ntu** [comment]
Hi, thanks for your contribution!

I've noticed that some translations on main branch have been a bit outdated so I've pushed a few commits to fix that. Could you please rebase this on master and update these translations based on the current state?

If you want I can also try helping a bit with the generating the updated bg.ts file (essentially running the lupdate command from the wiki) and you edit it, but I'm quite sure you opening the Qt Linguist tool itself, opening bg.ts file and seeing which translations are missing shouldn't take too much time.

**Comment by ShinniUwU** [comment]
Hi,

Thank you for your message and for guiding me through this process.

This is my first time contributing or translating something, so I'm still learning the ropes. I've successfully rebased my changes onto the main branch, but I'm unsure about how to proceed with updating the translations using Qt Linguist. Could you please provide me with some guidance on how to inform Qt Linguist about the missing translations and how to add them?

Best regards,
Hana

**Comment by z3ntu** [comment]
Sure, no problem. I've pushed a commit to your branch that updates it. I've included the command in the commit message for your info, it's the same as written in the wiki page on top https://github.com/z3ntu/RazerGenie/wiki/Translations

Now Qt Linguist should look like this if you open the file:

image

For all the strings with a yellow checkmark and question marks, enter the translation and click the green arrow in the toolbar ("Mark item as done").

Also some strings are marked as "disappeared" which are the ones grayed out and with a gray checkmark. You can basically ignore them, they're just strings that were part of the source code before, but not anymore in the current version.

**Comment by ShinniUwU** [comment]
Hey did I do everything right?

**Comment by z3ntu** [comment]
Yeah looks good!

To translate the strings like "Scroll Wheel" and "Spectrum" you'll need to also create a translation inside libopenrazer: https://github.com/z3ntu/libopenrazer/tree/main/translations Same as here, you could copy-paste the libopenrazer_de.ts and update meson.build there.

image

**Review by z3ntu — APPROVED** [review]
Thanks!

**Pull request merged**
