### PR TITLE
Add Russian layout

### PR DESCRIPTION
**Pull request by theskymaybe**

### CODE REVIEW

**Comment by z3ntu** [comment]
Thanks for the PR! It seems you added the layout twice though, one with english(?) labels and once with cyrillic labels? I guess this is not on purpose or is it?

**Comment by theskymaybe** [comment]
> Thanks for the PR! It seems you added the layout twice though, one with english(?) labels and once with cyrillic labels? I guess this is not on purpose or is it?

Sure, that happened by an accident. Sorry ^^

**Comment by z3ntu** [comment]
I've corrected the mistake and compared the layout with this image: https://static.razer.ru/133708/bw_elite_wr_2018_ru_ui.png
image

Are you happy with this?

**Comment by theskymaybe** [comment]
Absolutely! Thank you very much <3

**Comment by z3ntu** [comment]
Sorry for the delay, it's merged now. Thanks again! :)

**Pull request merged**
