### PR TITLE
Add missing space & fn matrix values for non-US kbd layouts

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by luk1337** [comment]
There are couple more layouts that don't seem to have matrix values for "fn" & "space", if you want i can amend this change to include them.

**Comment by z3ntu** [comment]
Yeah please do for all layouts in this file. Some keyboards like my BlackWidow Chroma don't have an LED on the space bar, that's why nobody added it :) 

What keyboard are you basing this on btw?

**Comment by luk1337** [comment]
Updated change.

The keyboard I'm using is BlackWidow X Chroma.

**Comment by z3ntu** [comment]
Thanks :)

**Pull request merged**
