### PR TITLE
Translation: add fr.ts

### PR DESCRIPTION
**Pull request by vankasteelj**
- done in QT4linguist
- tested with `lrelease` on RazerGenie 0.8.1

### CODE REVIEW

**Comment by z3ntu** [comment]
Please also add the new language in `data/CMakeLists.txt` .

**Comment by vankasteelj** [comment]
should it be added with a comma? on the same line as 'de.ts'? It's unclear

**Comment by z3ntu** [comment]
Thanks for the translations!
I haven't looked closer yet because I don't know French and can't really verify that those translations are correct :wink: I'll try to get this in before the next (probably big) release.

**Comment by vankasteelj** [comment]
It should be okay as I don't usually do misspels or grammar faults, it's my mothertongue. However, the community should feel free to update/correct if needed

**Comment by z3ntu** [comment]
I rather meant that I cannot verify that the translations are accurate and not something you dreamt up :P

**Comment by z3ntu** [comment]
I'd like to ask you to update the translations in the branch `razer_test-fr-translations` , I've taken the translations from this PR and updated the file so it matches the new codebase. Also some of the translations moved to https://github.com/z3ntu/libopenrazer so I would appreciate you updating both those translations :)

**Pull request merged**
