### PR TITLE
 Add en_US layout for Razer Blade Stealth (Late 2017)

### PR DESCRIPTION
**Pull request by vamc19**
Screenshot of the editor:

image

Tested it on my laptop with OpenRazer v2.3.0

### CODE REVIEW

**Comment by z3ntu** [comment]
Thanks for the PR!
Right shift and enter (or caps&left shift) are missing 2 pixels of width, other than that it looks good!

**Comment by vamc19** [comment]
My bad, round-off error. I also messed up the alignment of 5th row. Fixed.

image

**Comment by z3ntu** [comment]
I'm guessing all keys in that layout activate the correct key in the keyboard?

**Comment by vamc19** [comment]
Yup

**Comment by z3ntu** [comment]
Merged as 9ecf5de, thanks!

**Pull request closed without merging**
