### PR TITLE
Individual support of side LEDs

### PR DESCRIPTION
**Pull request by nightsky30**
Added support for side LEDs on the Lancehead TE with RazerGenie:

Set individual effects on Scroll, Logo, Left LED row, Right LED row
Set individual brightness on Scroll, Logo, Left LED row, Right LED row

This is to accompany https://github.com/openrazer/openrazer/pull/833 and complements https://github.com/openrazer/openrazer/pull/850 in that the user now has the option to set them individually or all at once.

### CODE REVIEW

**Comment by z3ntu** [comment]
yay for code duplication \o/

**Comment by nightsky30** [comment]
Yeah, it definitely could be done better :(

**Comment by z3ntu** [comment]
Nah it's fine like that. With the current openrazer daemon, a better design isn't possible I think.

**Comment by nightsky30** [comment]
Maybe modifying it to somehow pass the identity or lighting location and using switch case statements in single sets of lighting functions to determine the LED to act upon?  I don't understand it well enough, but do agree I hate seeing the same code duplicated many times.  Good indicator something could be done differently.  I will say I do like the way razer_test is organized.  Seems a lot more streamlined for code reuse and extensibility.

**Comment by tildearrow** [comment]
Bug because you disabled issues in your project: Setting the wave direction for a zone kills the radio options for the other zones which are set to Wave.

**Comment by z3ntu** [comment]
I haven't forgotten about this pull request, but I've been working on a way to not have to duplicate all this code. I hope this will method will work, as I've only completed parts of it for now.
This would also unify the two active RazerGenie branches (master & razer_test).

And here's a screenshot of the GUI showing for the first time with this method (doing basically anything with the GUI will crash it for now^^):
Screenshot_20190731_155751

**Comment by z3ntu** [comment]
You can try:
```
git clone https://github.com/z3ntu/RazerGenie -b razer_test
cd RazerGenie
git clone https://github.com/z3ntu/libopenrazer -b old-openrazer subprojects/libopenrazer
meson builddir
ninja -C builddir
./builddir/src/razergenie
```
Everything should work with that but I would be glad if you could test it thoroughly. Custom layouts won't work because I use different names in that branch (e.g. `German` instead of `de_DE`) but I'll fix that soon

**Comment by nightsky30** [comment]
> You can try:
> 
> ```
> git clone https://github.com/z3ntu/RazerGenie -b razer_test
> cd RazerGenie
> git clone https://github.com/z3ntu/libopenrazer -b old-openrazer subprojects/libopenrazer
> meson builddir
> ninja -C builddir
> ./builddir/src/razergenie
> ```
> 
> Everything should work with that but I would be glad if you could test it thoroughly. Custom layouts won't work because I use different names in that branch (e.g. `German` instead of `de_DE`) but I'll fix that soon
> 
> edit: I think like that the build would fail because it doesn't find `razer_test.h`. I think you should be able to solve that by dropping this header: https://raw.githubusercontent.com/z3ntu/razer_test/master/include/razer_test.h into the `subprojects/libopenrazer/include/` folder. If that doesn't work, you can always put the header into `/usr/include/`

I built and tested both with and without `subprojects/libopenrazer/include/razer_test.h`.  The build worked the same either way.  RazerGenie v0.7 and OpenRazer 2.6.0 were reported.

**Keyboard - BlackWidow Chroma V2
Mousemat - Firefly
Mouse - Lancehead TE**

The following applies for all devices and all lighting sections:

- Brightness is either Off or On.  There is no progressive brightening/dimming with the slider bars.
  - 0 - 99 == off
  - 100 == on

- Wave direction only works wave right/up, not down/left.

- Reactive color fade is very slow, and the selected colors are not used.  Maybe the red values are not being passed properly?
  - Selecting a red color produces a green effect
  - Selecting a green color produces a blue effect
  - Selecting a orange/yellow color produces a cyan effect

**Reactive obviously is not currently working with the Firefly.

**Comment by z3ntu** [comment]
> I built and tested both with and without subprojects/libopenrazer/include/razer_test.h. The build worked the same either way.

It could be that because RazerGenie has razer_test as a meson subproject that the header got available for libopenrazer as well. Good to know.

> Brightness is either Off or On. There is no progressive brightening/dimming with the slider bars.

Probably an issue of the 0-255 to 0-100 brightness conversion and data types. Will look into it.

> Wave direction only works wave right/up, not down/left.

I'm guessing I'm not "translating" the direction values correctly.

> Reactive color fade is very slow, and the selected colors are not used. Maybe the red values are not being passed properly, or there is a parameter order issue?

The speed issue is probably similar as with Wave. Colors are probably a parameter order issue.

> The default window dimensions could be enlarged to allow the different sections to be more visible like your screenshot above.

I have to implement a scroll view for the main container. When I started the project, there was no device with so many options available^^

> Device images were not populating. (NM, think it's a FIXME)

Yes, I'll make the API in libopenrazer nicer; currently it's not supported.

> Ripple and Ripple Random effects were not available for the BW Chroma V2.

Not implemented (yet), but probably won't be implemented soon because it isn't on of the hardware effects, but a custom effect in the openrazer daemon. I'll have to think about a nice API to call them.

**Comment by z3ntu** [comment]
Brightness, wave & reactive are fixed, device images are also available again. I'll look into the scroll view now (it's long overdue anyways)

**Comment by nightsky30** [comment]
Thanks, brightness, wave, reactive, and images are all working wonderfully now! :+1:

**Comment by z3ntu** [comment]
I've pushed a few more commits. The scroll "area" is now implemented and the custom editor should work as well now.

The remaining to-do items are ripple and checking if I didn't break anything for old simple devices (I certainly did)

**Comment by nightsky30** [comment]
The scroll bar is working well as is the custom editor (other than the mouse). :+1:   I'd help with testing the older devices, but I don't own any.

**Comment by z3ntu** [comment]
I fixed a bunch of stuff now for other devices and I haven't encountered any issues yet.

Todo now:
* Ripple / custom daemon effects (maybe I'll leave that out initially when making that branch master, but definitely before a release using that state). I'll probably make a libopenrazer API `QStringList getSoftwareEffects()` and `bool setSoftwareEffect(QString effect)` or something, where the effects are hardcoded for openrazer, but dynamic for razer_test. In razer_test I'll have to re-do the API a bit there but it wasn't good anyways
* Getting rid of the razer_test dependency for the openrazer target. I'll probably include the file directly in libopenrazer but it'll be renamed to `openrazer.h` (plus a bunch of namespace changes for that)

**Comment by tildearrow** [comment]
> Ripple / custom daemon effects (maybe I'll leave that out initially when making that branch master, but definitely before a release using that state). I'll probably make a libopenrazer API QStringList getSoftwareEffects() and bool setSoftwareEffect(QString effect) or something, where the effects are hardcoded for openrazer, but dynamic for razer_test. In razer_test I'll have to re-do the API a bit there but it wasn't good anyways

I aim to experiment with this after finishing effect storage.

**Comment by nightsky30** [comment]
@z3ntu The last device image appears normal when RazerGenie loads.  But **sometimes** when modifying RazerGenie's window dimensions I am seeing the last device image distorted.  It appears to be squished.  The behavior doesn't happen every time when using RazerGenie.  But when it does happen it only happens when either of the other devices are selected at the time of window dimension modification.  Conversely if I select the last device and modify the window dimensions again it will correct the distorted device image.  I made sure it happened with all devices by unplugging and plugging them in again to switch the order.  I also removed a device and tested it again with just two.  When it happens it always affects the last device in the list.

Screenshot_2019-08-19_16-48-37
Screenshot_2019-08-19_17-08-01
Screenshot_2019-08-19_17-39-15

**Comment by z3ntu** [comment]
I'm going to write that one off as a Qt bug because I don't do any sort of size adjustments in my code

This here is essentially the code for the image in the list:
```cpp
    QPixmap icon(path);
    QPixMap scaled = icon.scaled(150, 75, Qt::KeepAspectRatio, Qt::SmoothTransformation);
    imageLabel = new QLabel(this);
    imageLabel->setPixmap(scaled);
    imageLabel->setAlignment(Qt::AlignCenter);
    imageLabel->setWordWrap(true);
    layout->addWidget(imageLabel);
```

**Comment by z3ntu** [comment]
The new codebase is in master now, so this is already supported there :) Still thanks for the PR!

**Pull request closed without merging**
